### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Tankium** [Muzuwi/AmmoboxPlus#5]
# **Environment**
 - Terraria version: 
 - tModLoader Version:
 - Ammobox Version:
 - Present mods (if applicable): 
More Endless Ammo v1.0.0.1
Gunner's Arsenal v0.6
# **Description**
A clear and concise description of what the issue is.
The wav sound file at Sounds/Custom/blackHole failed to load
(Try making sure your computer has speakers attached and audio devices enabled)
   at Terraria.ModLoader.Mod.LoadWav(String path, Byte[] bytes)
   at Terraria.ModLoader.Mod.LoadResourceFromStream(String path, Int32 len, BinaryReader reader)
   at Terraria.ModLoader.IO.TmodFile.Read(LoadedState desiredState, ReadStreamingAsset streamingHandler)
   at Terraria.ModLoader.ModLoader.do_Load(Object threadContext)

Inner Exception:
An unexpected error has occurred.
   at Microsoft.Xna.Framework.Audio.SoundEffect.AllocateFormatAndData(Byte[] format, Byte[] data, Int32 offset, Int32 count)
   at Microsoft.Xna.Framework.Audio.SoundEffect..ctor(Stream stream)
   at Microsoft.Xna.Framework.Audio.SoundEffect.FromStream(Stream stream)
   at Terraria.ModLoader.Mod.LoadWav(String path, Byte[] bytes)
# **Steps To Reproduce**
A list of steps to reproduce the issue
1) enable this mod
2) load a world
# **Expected behavior**
the window not to crash
# **Screenshots**

# **Additional context**

**Comment by Tankium** [comment]
Whoops forgot versions of things:
Terraria: 1.3.5.2
tModLoader: 0.10.1.5
Ammobox: 1.4.4.1

**Comment by Muzuwi** [comment]
Thanks for the report.
Do you have any audio devices enabled at all in your OS, as per the message says? I am able to reproduce this but only when all the audio devices in the system are disabled. 
I've tested this behavior with other mods, and it seems like tModLoader requires an audio device to be enabled for custom sounds to load properly, or else a crash occurs and the mod gets disabled. There's not much I can do on my end.

**Comment by Tankium** [comment]
Is there a way by any chance you could message the maker of tModLoader
about this crash? Also I got headphones and I will see if enabling this
device helps

**Comment by Muzuwi** [comment]
This appears to have been fixed on tModLoader v0.11.x
